<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>

<fieldset class="fieldset" data-role="filter">
    <div class="field value required">
        <label class="label" for="filter_value"><span><?php echo __('Search') ?></span></label>

        <div class="control">
            <input type="text" class="input-text" data-role="filter-value" id="filter_value">
        </div>
    </div>
</fieldset>
