<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="nav navbar-nav navbar-right mini-cart">

  <div class="hidden-xs search-bar-container">
  <p class="search-icon">
  <a><span class="glyphicon glyphicon-search" aria-hidden="true"></span></a>
  </p>

<form class=" pull-left" role="search" id="search_mini_form"
      action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
    <div class="form-search">
        <input data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete",
                                "responseFieldElements":"ul li",
                                "selectClass": "active",
                                "template": "<li class=\"<%- data.row_class %>\" id=\"qs-option-<%- data.index %>\" role=\"option\"><a href=\"#\" onclick=\"return false;\"><span class=\"qs-option-name\"><%- data.title %></span><span aria-hidden=\"true\" class=\"amount\"><%- data.num_results %></span></a></li>"
                                }
                           }'
               type="text"
               name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
               value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
               placeholder="<?php /* @escapeNotVerified */ echo __('Hey.. What are you looking for?'); ?>"
               class="form-control"
               maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
               role="combobox"
               aria-haspopup="false"
               aria-autocomplete="both"
               autocomplete="off">
    </div>
    <button type="submit" title="Search" class="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>


    <div id="search_autocomplete" class="search-autocomplete"></div>
    <?php echo $block->getChildHtml() ?>
</form>
</div>
</div>
<script >
  require(['jquery', 'jquery/ui'], function($){ 
     
     jQuery(document).ready(function($) {
       jQuery('.glyphicon-search').on('click', function(event) {
         event.preventDefault();
         /* Act on the event */
         jQuery('#search_mini_form').toggle();
       });
     }); 
 });


</script>
